title: After Dark
description: A simple, yet highly configurable responsive dark theme for Hugo.
google_analytics: UA-6473963-12
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
